# Generated by `rjournal_article()` using `knitr::purl()`: do not edit by hand
# Please edit lineeGuida.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE)

